# Generated by Django 5.2.11 on 2026-02-08 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "time"], name="habits_habi_user_id_0c9228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["is_public"], name="habits_habi_is_publ_af85bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["last_completed"], name="habits_habi_last_co_0e3451_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("execution_time__lte", 120)),
                name="execution_time_max_120",
            ),
        ),
    ]
